spring:
  #  profiles:
  #    active: dev
  application:
    name: simple-coupons-api
  datasource:
    url: jdbc:postgresql://postgres:${PG_PORT:5432}/${PG_DATABASE:coupons_db}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080