services:
  postgres:
    container_name: coupons-postgres
    image: postgres:12.1-alpine
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}